# Funciones convexas diferenciables

---

En este notebook, aprenderemos a:

- Usar Autograd y Sympy para calcular gradiente y hessianas.
- Analizar convexidad.

### Metodología

- En grupos (idealmente de dos personas), resolver los problemas en Python (*chatGPT allowed*).
---


## Librerías

Utilizaremos dos paquetes principales para este análisis:

- [Autograd](https://github.com/HIPS/autograd): Utilizaremos Autograd para calcular el gradiente y el hessiana de nuestra función objetivo. Autograd utiliza la diferenciación automática para realizar estos cálculos de manera eficiente y precisa.
- [Sympy](https://www.sympy.org/): Sympy es una biblioteca de Python para cálculos simbólicos. La utilizaremos para calcular analíticamente el gradiente y el hessiana, lo cual nos permite realizar un análisis detallado y comprender mejor la estructura de las funciones.

Ambos paquetes son herramientas complementarias: mientras Autograd nos permite realizar cálculos numéricos, Sympy nos facilita la manipulación simbólica de expresiones matemáticas.

Para instalar las librerías necesarias, puede ejecutar los siguientes comandos:

In [1]:
# !pip install autograd
# !pip install sympy

In [2]:
import numpy as np
from autograd import grad, jacobian, hessian
import sympy as sp

# Autograd y Sympy


### Funciones univariantes

Supongamos que tenemos la función $f(x)=5x+10$ (una recta), y queremos evaluar $\nabla f(x_0=1)$

In [26]:
def f(x):
    return (x[0]-3)**2+()

gradiente = grad(f)

x0 = 3.0

print('El gradiente en x0 es:', gradiente(x0))

El gradiente en x0 es: 2.0


In [3]:
def f(x):
    return 5*x+10

gradiente = grad(f)

x0 = 1.0

print('El gradiente en x0 es:', gradiente(x0))

El gradiente en x0 es: 5.0


In [4]:
# Definir la variable simbólica
x = sp.symbols('x')

# Definir la función de manera simbólica
f = 5*x + 10

# Calcular el gradiente (derivada) de la función
gradiente = sp.diff(f, x)

# Evaluar el gradiente en x0
x0 = 1.0
gradiente_en_x0 = gradiente.subs(x, x0)

print('El gradiente en x0 es:', gradiente_en_x0)


El gradiente en x0 es: 5


### Funciones multivariantes

Supongamos que tenemos definimos el plano $f(x_1,x_2)=5x_1+10x_2+4$, y queremos evaluar en $\mathbf{x}_0=[1,2]^{\top}$:

- $\nabla f(\mathbf{x}_0)$
- $\mathbf{H}_f(\mathbf{x}_0)$

In [5]:
def plano(x): 
    return 5*x[0] + 10*x[1] + 4

x0 = np.array([1,2],dtype=float)

gradiente = grad(plano)
hessiana = hessian(plano)

print('El gradiente en x0 es:', gradiente(x0))
print('La hessiana en x0 es:\n', hessiana(x0))

El gradiente en x0 es: [ 5. 10.]
La hessiana en x0 es:
 [[0. 0.]
 [0. 0.]]


/home/vacek/anaconda3/lib/python3.7/site-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")


In [6]:
# Definir las variables simbólicas
x1, x2 = sp.symbols('x1 x2')

# Definir la función de manera simbólica
def plano_sympy(x1, x2):
    return 5*x1 + 10*x2 + 4

# Calcular el gradiente de la función
gradiente_sympy = sp.Matrix([sp.diff(plano_sympy(x1, x2), var) for var in (x1, x2)])

# Calcular la matriz Hessiana
hessiana_sympy = sp.hessian(plano_sympy(x1, x2), (x1, x2))

# Evaluar el gradiente y el hessiana en x0
x0 = np.array([1, 2], dtype=float)
gradiente_en_x0 = gradiente_sympy.subs({x1: x0[0], x2: x0[1]})
hessiana_en_x0 = hessiana_sympy.subs({x1: x0[0], x2: x0[1]})

print('El gradiente en x0 es:', gradiente_en_x0)
print('La hessiana en x0 es:\n', hessiana_en_x0)

El gradiente en x0 es: Matrix([[5], [10]])
La hessiana en x0 es:
 Matrix([[0, 0], [0, 0]])


### Funciones paramétricas

Supongamos que tenemos definimos el plano $f(x_1,x_2)=ax_1+bx_2+4$, y queremos evaluar en $\mathbf{x}_0=[1,2]^{\top}$:

- $\nabla f(\mathbf{x}_0)$
- $\mathbf{H}_f(\mathbf{x}_0)$

In [7]:
def plano_con_parametros(x,a,b):
    return a*x[0] + b*x[1] + 4

a = 5 
b = 10

x0 = np.array([1,2],dtype=float)

gradiente = grad(plano_con_parametros)
hessiana = hessian(plano_con_parametros)

print('El gradiente en x0 es:', gradiente(x0,a,b))
print('La hessiana en x0 es:\n', hessiana(x0,a,b))

El gradiente en x0 es: [ 5. 10.]
La hessiana en x0 es:
 [[0. 0.]
 [0. 0.]]


In [8]:
# Definir las variables simbólicas
x1, x2, a, b = sp.symbols('x1 x2 a b')

# Definir la función de manera simbólica, incluyendo los parámetros a y b
def plano_con_parametros_sympy(x1, x2, a, b):
    return a*x1 + b*x2 + 4

# Calcular el gradiente de la función
gradiente_sympy = sp.Matrix([sp.diff(plano_con_parametros_sympy(x1, x2, a, b), var) for var in (x1, x2)])

# Calcular la matriz Hessiana
hessiana_sympy = sp.hessian(plano_con_parametros_sympy(x1, x2, a, b), (x1, x2))

# Valores de a, b y x0
a_val = 5
b_val = 10
x0 = np.array([1, 2], dtype=float)

# Evaluar el gradiente y el hessiana en x0, a y b
gradiente_en_x0 = gradiente_sympy.subs({x1: x0[0], x2: x0[1], a: a_val, b: b_val})
hessiana_en_x0 = hessiana_sympy.subs({x1: x0[0], x2: x0[1], a: a_val, b: b_val})

print('El gradiente en x0 es:', gradiente_en_x0)
print('La hessiana en x0 es:\n', hessiana_en_x0)


El gradiente en x0 es: Matrix([[5], [10]])
La hessiana en x0 es:
 Matrix([[0, 0], [0, 0]])


# Ejercicio 1

Calcule el gradiente y el hessiana de la función $$f(\mathbf{x}) = 2x_1 + 6x_2 - 2x_1^2 - 3x_2^2 + 4x_1x_2 $$ en $\mathbf{x_0}=(0, 0)$

In [9]:
# your code here
# ...

In [10]:
# Definir la función usando autograd
def f_autograd(x):
    return 2*x[0] + 6*x[1] - 2*x[0]**2 - 3*x[1]**2 + 4*x[0]*x[1]

# Calcular el gradiente y el hessiana usando autograd
grad_f_autograd = grad(f_autograd)
hess_f_autograd = hessian(f_autograd)

# Punto de evaluación
x0_autograd = np.array([0, 0], dtype=float)

# Evaluar el gradiente y el hessiana en x0
grad_en_x0_autograd = grad_f_autograd(x0_autograd)
hess_en_x0_autograd = hess_f_autograd(x0_autograd)

print('El gradiente en x0 es:', grad_en_x0_autograd)
print('El hessiana en x0 es:\n', hess_en_x0_autograd)

El gradiente en x0 es: [2. 6.]
El hessiana en x0 es:
 [[-4.  4.]
 [ 4. -6.]]


In [11]:
# Definir las variables simbólicas
x1, x2 = sp.symbols('x1 x2')

# Definir la función de manera simbólica
f_sympy = 2*x1 + 6*x2 - 2*x1**2 - 3*x2**2 + 4*x1*x2

# Calcular el gradiente de la función
gradiente_sympy = sp.Matrix([sp.diff(f_sympy, var) for var in (x1, x2)])

# Calcular la matriz Hessiana
hessiana_sympy = sp.hessian(f_sympy, (x1, x2))

# Evaluar el gradiente y el hessiana en x0
x0_sympy = sp.Matrix([0, 0])
gradiente_en_x0_sympy = gradiente_sympy.subs({x1: x0_sympy[0], x2: x0_sympy[1]})
hessiana_en_x0_sympy = hessiana_sympy.subs({x1: x0_sympy[0], x2: x0_sympy[1]})

print('El gradiente en x0 es:', gradiente_en_x0_sympy)
print('El hessiana en x0 es:\n', hessiana_en_x0_sympy)

El gradiente en x0 es: Matrix([[2], [6]])
El hessiana en x0 es:
 Matrix([[-4, 4], [4, -6]])


# Ejercicio 2

Estudiar la convexidad de $$f(\mathbf{x}) = x_1x_2 + 2x_1^2 + x_2^2 - 6x_1x_3 $$


In [12]:
def autovalores(A):
    return np.linalg.eigvals(A)

In [13]:
# your code here
# ...

In [14]:
# Definir las variables simbólicas
x1, x2, x3 = sp.symbols('x1 x2 x3')

# Definir la función de manera simbólica
f_sympy = x1*x2 + 2*x1**2 + x2**2 - 6*x1*x3

# Calcular la matriz Hessiana
hessiana_sympy = sp.hessian(f_sympy, (x1, x2, x3))

hessiana_sympy


Matrix([
[ 4, 1, -6],
[ 1, 2,  0],
[-6, 0,  0]])

In [15]:
# Convertir la matriz Hessiana a una matriz NumPy para evaluar los autovalores
hessiana_numpy = np.array(hessiana_sympy).astype(np.float64)

# Función para calcular los autovalores de una matriz
def autovalores(A):
    return np.linalg.eigvals(A)

# Calcular los autovalores de la matriz Hessiana
autovalores_hessiana = autovalores(hessiana_numpy)

autovalores_hessiana

array([ 8.42737652, -4.3785932 ,  1.95121668])

# Ejercicio 3

Estudiar la convexidad de $$f(\mathbf{x}) = 10 - 2(x_2 - x_1^2)^2 $$


In [16]:
# your code here
# ...

In [17]:
# Definir las variables simbólicas
x1, x2 = sp.symbols('x1 x2')

# Definir la función de manera simbólica
f_sympy = 10 - 2*(x2 - x1**2)**2

# Calcular la matriz Hessiana
hessiana_sympy = sp.hessian(f_sympy, (x1, x2))

hessiana_sympy

Matrix([
[-24*x1**2 + 8*x2, 8*x1],
[            8*x1,   -4]])

In [18]:
# Definir las desigualdades
inequality1 = 8*x2 - 24*x1**2 >= 0
inequality2 = -32*x2 + 96*x1**2 - 64*x1**2 >= 0

# Simplificar la segunda desigualdad
inequality2_simplified = -32*x2 + 32*x1**2 >= 0

# Resolver las desigualdades
solution1 = sp.solve(inequality1, x2)
solution2 = sp.solve(inequality2_simplified, x2)

solution1, solution2

(x2 >= 3*x1**2, x2 <= x1**2)

# Ejercicio 4

Estudiar la convexidad de $$f(\mathbf{x}) = x^2 + 3y^2 + z^2 + xy - 4z - 5x + 14 $$


In [ ]:
# your code here
# ...

In [ ]:
# Definir las variables simbólicas
x1, x2, x3 = sp.symbols('x1 x2 x3')

# Definir la función de manera simbólica
f_sympy = x1**2 + 3*x2**2 + x3**2 + x1*x2 - 4*x3 - 5*x1 + 14

# Calcular la matriz Hessiana
hessiana_sympy = sp.hessian(f_sympy, (x1, x2, x3))

# Convertir la matriz Hessiana a una matriz NumPy
hessiana_numpy = np.array(hessiana_sympy).astype(np.float64)

# Calcular los autovalores de la matriz Hessiana
autovalores_hessiana = np.linalg.eigvals(hessiana_numpy)

autovalores_hessiana